# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1605c5fc361873d5a6847b9679fff6b1fab004b43f2645e2f519223e299f46a3d177d36eea94ad68cd0a1b4451a4780341292eb9809c5f26e19800e5b1db507a

test:
  secret_key_base: 9b69570944416edf50ac092706ce844d2d51af6fb34337539cfe23e225adb7eaed1db71578778ab3e2414003bfa5d5cf87cfa6f98b6db67778a58adbfdbe066c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
